### ISSUE TITLE
Best practices TODO

### ISSUE THREAD

**Issue by anandbaburajan** [FOSS-Cell-GECPKD/interpreter#11]
### Code
* [ ] Proper readable and maintable code with consistent spacing and indentation
* [ ] Functions follow the "Do One Thing" rule (single-responsibility)
* [ ] Followed the SOLID principles (OOP)
* [ ] Followed DRY (Don’t Repeat Yourself)
* [ ] Added comments wherever required
* [ ] Proper naming conventions
* [ ] Avoided deep nesting

### Readme
* [ ] Badges (similar to the Gitter badge. You can maybe use: https://shields.io/)
* [ ] Description (why this project exists)
* [ ] Features (working of the project)
* [ ] Setup (Quick start instructions with how to download and use your project)
* [ ] Contributing (How can others contribute?)
* [ ] Thanks to (List of contributors)
* [ ] License ("This project is licensed under the <your license>")

### Tests and CI/CD
* [ ] Wrote tests
* [ ] Deployed the project (if possible)
* [ ] Added CI/CD tools to your project (maybe CircleCI or TravisCI) (if possible)
